/**
 * This file is auto-generated by scripts/buildNestedTokens.js
 * Do not edit manually.
 */

export declare const theme: {
  colors: {
    brandPrimary: string;
    brandWhite: string;
    brandBlack: string;
    baseGrey100: string;
    baseGrey200: string;
    baseGrey300: string;
    baseGrey400: string;
    baseBlue100: string;
    baseBlue200: string;
    baseBlue300: string;
    baseBlue400: string;
    backgroundDefault: string;
    functionsError: string;
    functionsWarning: string;
    functionsSuccess: string;
    functionsDisabled: string;
  };
  radius: {
    xs: string;
    md: string;
  };
  shadow: {
    xs: string;
    md: string;
  };
  spacing: {
    xs: string;
    sm: string;
    lg: string;
  };
  typography: {
    headline: {
      desktop: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        sm: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xs: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
      mobile: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        sm: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xs: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
    };
    buttonDesktopFontSize: string;
    buttonDesktopLineHeight: string;
    buttonDesktopFontFamily: string;
    buttonMobileFontSize: string;
    buttonMobileLineHeight: string;
    buttonMobileFontFamily: string;
    action: {
      desktop: {
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
      mobile: {
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
    };
    subline: {
      desktop: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        sm: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xs: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
      mobile: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        sm: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xs: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
    };
    text: {
      desktop: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
      mobile: {
        xxl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        xl: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        lg: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
        md: {
          fontSize: string;
          lineHeight: string;
          fontFamily: string;
        };
      };
    };
  };

};
