/**
 * This file is auto-generated by scripts/buildNestedTokens.js
 * Do not edit manually.
 */

export const theme = {
  "colors": {
    "brandPrimary": "#23ABC2",
    "brandWhite": "#FFFFFF",
    "brandBlack": "#1A1C1E",
    "baseGrey100": "#455458",
    "baseGrey200": "#7B898C",
    "baseGrey300": "#CED8DA",
    "baseGrey400": "#ECEFF2",
    "baseBlue100": "#0F8FA5",
    "baseBlue200": "#4D828D",
    "baseBlue300": "#E3EFF1",
    "baseBlue400": "#E3F3F6",
    "backgroundDefault": "#F2FAFB",
    "functionsError": "#F73946",
    "functionsWarning": "#FF6D00",
    "functionsSuccess": "#76B228",
    "functionsDisabled": "#B9C4C8"
  },
  "radius": {
    "xs": "10px",
    "md": "18px"
  },
  "shadow": {
    "xs": "0px 4px 54.3px 14px rgba(0, 0, 0, 0.07)",
    "md": "0px 16px 24px -8px rgba(0, 37, 48, 0.18)"
  },
  "spacing": {
    "xs": "14px",
    "sm": "25px",
    "lg": "30px"
  },
  "typography": {
    "fontFamilyHeadline": "'Manrope', sans-serif",
    "fontFamilyBody": "'Sora', sans-serif",
    "headline": {
      "desktop": {
        "xxl": {
          "fontSize": "54px",
          "lineHeight": "62px"
        },
        "xl": {
          "fontSize": "42px",
          "lineHeight": "55px"
        },
        "lg": {
          "fontSize": "32px",
          "lineHeight": "40px"
        },
        "md": {
          "fontSize": "24px",
          "lineHeight": "32px"
        },
        "sm": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "xs": {
          "fontSize": "15px",
          "lineHeight": "24px"
        }
      },
      "mobile": {
        "xxl": {
          "fontSize": "32px",
          "lineHeight": "40px"
        },
        "xl": {
          "fontSize": "27px",
          "lineHeight": "36px"
        },
        "lg": {
          "fontSize": "22px",
          "lineHeight": "32px"
        },
        "md": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "sm": {
          "fontSize": "15px",
          "lineHeight": "24px"
        },
        "xs": {
          "fontSize": "13px",
          "lineHeight": "20px"
        }
      }
    },
    "buttonDesktopFontSize": "15px",
    "buttonDesktopLineHeight": "24px",
    "buttonMobileFontSize": "13px",
    "buttonMobileLineHeight": "20px",
    "action": {
      "desktop": {
        "xl": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "lg": {
          "fontSize": "15px",
          "lineHeight": "24px"
        },
        "md": {
          "fontSize": "11px",
          "lineHeight": "18px"
        }
      },
      "mobile": {
        "xl": {
          "fontSize": "16px",
          "lineHeight": "24px"
        },
        "lg": {
          "fontSize": "13px",
          "lineHeight": "20px"
        },
        "md": {
          "fontSize": "11px",
          "lineHeight": "18px"
        }
      }
    },
    "subline": {
      "desktop": {
        "xxl": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "xl": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "lg": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "md": {
          "fontSize": "15px",
          "lineHeight": "20px"
        },
        "sm": {
          "fontSize": "13px",
          "lineHeight": "20px"
        },
        "xs": {
          "fontSize": "13px",
          "lineHeight": "20px"
        }
      },
      "mobile": {
        "xxl": {
          "fontSize": "15px",
          "lineHeight": "24px"
        },
        "xl": {
          "fontSize": "15px",
          "lineHeight": "24px"
        },
        "lg": {
          "fontSize": "13px",
          "lineHeight": "20px"
        },
        "md": {
          "fontSize": "11px",
          "lineHeight": "18px"
        },
        "sm": {
          "fontSize": "11px",
          "lineHeight": "18px"
        },
        "xs": {
          "fontSize": "11px",
          "lineHeight": "18px"
        }
      }
    },
    "text": {
      "desktop": {
        "xxl": {
          "fontSize": "22px",
          "lineHeight": "32px"
        },
        "xl": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "lg": {
          "fontSize": "15px",
          "lineHeight": "24px"
        },
        "md": {
          "fontSize": "13px",
          "lineHeight": "20px"
        }
      },
      "mobile": {
        "xxl": {
          "fontSize": "18px",
          "lineHeight": "28px"
        },
        "xl": {
          "fontSize": "16px",
          "lineHeight": "24px"
        },
        "lg": {
          "fontSize": "13px",
          "lineHeight": "20px"
        },
        "md": {
          "fontSize": "11px",
          "lineHeight": "18px"
        }
      }
    }
  }
};
