import { readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

// Setup __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Input/output paths
const tokensFile = path.resolve(__dirname, "../theme/theme.js");
const outputFile = path.resolve(__dirname, "../theme/themeNested.ts");

// === Types ===

type NestedTokens =
  | string
  | {
      [key: string]: NestedTokens;
    };

// === Utilities ===

function toCamelCase(str: string): string {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function deepSet(
  obj: Record<string, NestedTokens>,
  keys: string[],
  value: string,
): void {
  let current: Record<string, NestedTokens> = obj;

  keys.forEach((key, index) => {
    const isLast = index === keys.length - 1;

    if (isLast) {
      current[key] = value;
    } else {
      if (typeof current[key] !== "object" || current[key] === null) {
        current[key] = {};
      }
      current = current[key] as Record<string, NestedTokens>;
    }
  });
}

function buildNestedTokens(
  flat: Record<string, string>,
): Record<string, NestedTokens> {
  const nested: Record<string, NestedTokens> = {};

  for (const [flatKey, value] of Object.entries(flat)) {
    let keys: string[];

    if (flatKey.startsWith("Color")) {
      keys = ["colors", toCamelCase(flatKey.replace(/^Color/, ""))];
    } else if (flatKey.startsWith("Radius")) {
      keys = ["radius", toCamelCase(flatKey.replace(/^Radius/, ""))];
    } else if (flatKey.startsWith("Shadow")) {
      keys = ["shadow", toCamelCase(flatKey.replace(/^Shadow/, ""))];
    } else if (flatKey.startsWith("Spacing")) {
      keys = ["spacing", toCamelCase(flatKey.replace(/^Spacing/, ""))];
    } else if (flatKey.startsWith("Typography")) {
      const match = flatKey.match(
        /^Typography([A-Z][a-z]+)(Desktop|Mobile)(Xxl|Xl|Lg|Md|Sm|Xs)(FontSize|LineHeight|FontFamily)$/,
      );
      if (match) {
        const [, style, device, size, property] = match;
        keys = [
          "typography",
          toCamelCase(style),
          toCamelCase(device),
          toCamelCase(size),
          toCamelCase(property),
        ];
      } else {
        keys = ["typography", toCamelCase(flatKey.replace(/^Typography/, ""))];
      }
    } else {
      keys = [toCamelCase(flatKey)];
    }

    deepSet(nested, keys, value);
  }

  return nested;
}

function generateTypeDefinition(
  obj: NestedTokens,
  indent = 2,
  level = 0,
): string {
  const pad = (lvl: number) => " ".repeat(lvl);
  if (typeof obj === "string") return "string;\n";

  return Object.entries(obj)
    .map(([key, val]) => {
      if (typeof val === "string") {
        return `${pad(level)}${key}: string;\n`;
      } else {
        return `${pad(level)}${key}: {\n${generateTypeDefinition(
          val,
          indent,
          level + indent,
        )}${pad(level)}};\n`;
      }
    })
    .join("");
}

// === Main Script ===

const fileContent = await readFile(tokensFile, "utf8");

const regex = /export const (\w+) = (.+);/g;
const flatTokens: Record<string, string> = {};

let match: RegExpExecArray | null;
while ((match = regex.exec(fileContent)) !== null) {
  const [, key, rawValue] = match;
  const value = rawValue.trim().replace(/^["']|["']$/g, "");
  flatTokens[key] = value;
}

const nestedTokens = buildNestedTokens(flatTokens);

// === Write nested theme file ===

const outputCode = `/**
 * This file is auto-generated by scripts/buildThemeNested.ts
 * Do not edit manually.
 */
export const theme = ${JSON.stringify(nestedTokens, null, 2)} as const;
`;

await writeFile(outputFile, outputCode, "utf8");
console.log(`✅ Nested tokens written to: ${outputFile}`);

// === Write .d.ts file ===

const typeDefPath = outputFile.replace(/\.ts$/, ".d.ts");

const dtsContent = `/**
 * This file is auto-generated by scripts/buildThemeNested.ts
 * Do not edit manually.
 */
export declare const theme: {
${generateTypeDefinition(nestedTokens)}
};
`;

await writeFile(typeDefPath, dtsContent, "utf8");
console.log(`✅ Type definitions written to: ${typeDefPath}`);
