// ESM-compatible script

import { readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

// Setup __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Adjust this path to point to your generated flat token file
const tokensFile = path.resolve(__dirname, "../theme/theme.js");
const outputFile = path.resolve(__dirname, "../theme/themeNested.js");

const fileContent = await readFile(tokensFile, "utf8");

// Match flat exports like: export const SomeName = "value";
const regex = /export const (\w+) = (.+);/g;

const flatTokens = {};

let match;
while ((match = regex.exec(fileContent)) !== null) {
  const [, key, rawValue] = match;
  const value = rawValue.trim().replace(/^["']|["']$/g, "");
  flatTokens[key] = value;
}

// Helpers
function toCamelCase(str) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function deepSet(obj, keys, value) {
  let current = obj;
  keys.forEach((key, i) => {
    if (i === keys.length - 1) {
      current[key] = value;
    } else {
      current[key] ||= {};
      current = current[key];
    }
  });
}

function buildNestedTokens(flat) {
  const nested = {};

  for (const [flatKey, value] of Object.entries(flat)) {
    let keys = [];

    if (flatKey.startsWith("Color")) {
      keys = ["colors", toCamelCase(flatKey.replace(/^Color/, ""))];
    } else if (flatKey.startsWith("Radius")) {
      keys = ["radius", toCamelCase(flatKey.replace(/^Radius/, ""))];
    } else if (flatKey.startsWith("Shadow")) {
      keys = ["shadow", toCamelCase(flatKey.replace(/^Shadow/, ""))];
    } else if (flatKey.startsWith("Spacing")) {
      keys = ["spacing", toCamelCase(flatKey.replace(/^Spacing/, ""))];
    } else if (flatKey.startsWith("Typography")) {
      const m = flatKey.match(
        /^Typography([A-Z][a-z]+)(Desktop|Mobile)(Xxl|Xl|Lg|Md|Sm|Xs)(FontSize|LineHeight|FontFamily)$/
      );
      if (m) {
        const [, style, device, size, property] = m;
        keys = [
          "typography",
          toCamelCase(style),
          toCamelCase(device),
          toCamelCase(size),
          toCamelCase(property),
        ];
      } else {
        keys = ["typography", toCamelCase(flatKey.replace(/^Typography/, ""))];
      }
    } else {
      keys = [toCamelCase(flatKey)];
    }

    deepSet(nested, keys, value);
  }

  return nested;
}

const nestedTokens = buildNestedTokens(flatTokens);

// Create output JS module
const outputCode = `/**
 * This file is auto-generated by scripts/buildNestedTokens.js
 * Do not edit manually.
 */

export const theme = ${JSON.stringify(nestedTokens, null, 2)};
`;

await writeFile(outputFile, outputCode, "utf8");

console.log(`✅ Nested tokens written to: ${outputFile}`);

// Generate .d.ts file with basic typing
const typeDefPath = outputFile.replace(/\.js$/, ".d.ts");

function generateTypeDefinition(nestedObj, indent = 2) {
  const pad = (level) => " ".repeat(level);

  function walk(obj, level) {
    let output = "";
    for (const key in obj) {
      const value = obj[key];
      if (typeof value === "string") {
        output += `${pad(level)}${key}: string;\n`;
      } else {
        output += `${pad(level)}${key}: {\n${walk(value, level + indent)}${pad(level)}};\n`;
      }
    }
    return output;
  }

  return `/**
 * This file is auto-generated by scripts/buildNestedTokens.js
 * Do not edit manually.
 */

export declare const theme: {
${walk(nestedTokens, indent)}
};
`;
}

const dtsContent = generateTypeDefinition(nestedTokens);
await writeFile(typeDefPath, dtsContent, "utf8");

console.log(`✅ Type definitions written to: ${typeDefPath}`);
